export type WhiteLabelSource = "project" | "organization" | "platform";

export type WhiteLabelResolved = {
  source: WhiteLabelSource;
  brandName: string;
  logoUrl: string | null;
  disclaimers: string[];
  showPlatformBranding: boolean;
};

export type WhiteLabelReportInput = {
  project_id: string | null;
  project: {
    client_name?: string | null;
    white_label_config?: unknown;
  } | null;
  organization: {
    name?: string | null;
    white_label_config?: unknown;
  };
};

export type PlatformDefaults = {
  brandName: string;
  logoUrl: string | null;
  disclaimers: string[];
  showPlatformBranding: boolean;
};

const DEFAULT_PLATFORM: PlatformDefaults = {
  brandName: "Diligence OS",
  logoUrl: null,
  disclaimers: ["Generated by Diligence OS. For informational purposes only."],
  showPlatformBranding: true
};

function asRecord(value: unknown): Record<string, unknown> {
  if (typeof value === "object" && value !== null && !Array.isArray(value)) {
    return value as Record<string, unknown>;
  }

  return {};
}

function nonEmptyString(value: unknown): string | null {
  if (typeof value !== "string") return null;
  const trimmed = value.trim();
  return trimmed.length > 0 ? trimmed : null;
}

function extractLogoUrl(config: Record<string, unknown>): string | null {
  return nonEmptyString(config.logo_url) ?? nonEmptyString(config.logo) ?? null;
}

function extractBrandName(config: Record<string, unknown>): string | null {
  return nonEmptyString(config.brand_name) ?? nonEmptyString(config.brandName) ?? nonEmptyString(config.name) ?? null;
}

function extractDisclaimers(config: Record<string, unknown>): string[] {
  const disclaimers = config.disclaimers;
  if (Array.isArray(disclaimers)) {
    const values = disclaimers.map((entry) => nonEmptyString(entry)).filter((entry): entry is string => entry !== null);
    if (values.length > 0) {
      return values;
    }
  }

  const singular = nonEmptyString(config.disclaimer);
  if (singular) {
    return [singular];
  }

  return [];
}

function extractShowPlatformBranding(config: Record<string, unknown>): boolean | null {
  if (typeof config.show_platform_branding === "boolean") {
    return config.show_platform_branding;
  }

  if (typeof config.include_platform_branding === "boolean") {
    return config.include_platform_branding;
  }

  return null;
}

function hasWhiteLabelSignals(config: Record<string, unknown>): boolean {
  return (
    extractLogoUrl(config) !== null ||
    extractBrandName(config) !== null ||
    extractDisclaimers(config).length > 0
  );
}

function normalizePlatformDefaults(input?: Partial<PlatformDefaults>): PlatformDefaults {
  if (!input) {
    return DEFAULT_PLATFORM;
  }

  return {
    brandName: nonEmptyString(input.brandName) ?? DEFAULT_PLATFORM.brandName,
    logoUrl: input.logoUrl === undefined ? DEFAULT_PLATFORM.logoUrl : input.logoUrl,
    disclaimers: Array.isArray(input.disclaimers) && input.disclaimers.length > 0 ? input.disclaimers : DEFAULT_PLATFORM.disclaimers,
    showPlatformBranding:
      typeof input.showPlatformBranding === "boolean"
        ? input.showPlatformBranding
        : DEFAULT_PLATFORM.showPlatformBranding
  };
}

export function platformDefaultsFromEnv(): PlatformDefaults {
  const defaultDisclaimer = DEFAULT_PLATFORM.disclaimers[0];
  const envBrandName = nonEmptyString(Deno.env.get("PLATFORM_BRAND_NAME"));
  const envLogoUrl = nonEmptyString(Deno.env.get("PLATFORM_LOGO_URL"));

  const disclaimersFromJson = Deno.env.get("PLATFORM_DISCLAIMERS_JSON");
  let envDisclaimers: string[] = [];
  if (disclaimersFromJson) {
    try {
      const parsed = JSON.parse(disclaimersFromJson) as unknown;
      if (Array.isArray(parsed)) {
        envDisclaimers = parsed.map((entry) => nonEmptyString(entry)).filter((entry): entry is string => entry !== null);
      }
    } catch {
      envDisclaimers = [];
    }
  }

  if (envDisclaimers.length === 0) {
    const single = nonEmptyString(Deno.env.get("PLATFORM_DISCLAIMER"));
    if (single) {
      envDisclaimers = [single];
    }
  }

  const showPlatformBrandingEnv = Deno.env.get("PLATFORM_SHOW_BRANDING");
  const showPlatformBranding =
    showPlatformBrandingEnv === undefined || showPlatformBrandingEnv === null
      ? DEFAULT_PLATFORM.showPlatformBranding
      : showPlatformBrandingEnv.toLowerCase() !== "false";

  return {
    brandName: envBrandName ?? DEFAULT_PLATFORM.brandName,
    logoUrl: envLogoUrl ?? DEFAULT_PLATFORM.logoUrl,
    disclaimers: envDisclaimers.length > 0 ? envDisclaimers : [defaultDisclaimer],
    showPlatformBranding
  };
}

export function resolveWhiteLabel(report: WhiteLabelReportInput, platformOverride?: Partial<PlatformDefaults>): WhiteLabelResolved {
  const platform = normalizePlatformDefaults(platformOverride);
  const projectConfig = asRecord(report.project?.white_label_config);
  const orgConfig = asRecord(report.organization?.white_label_config);

  const projectFallbackName = nonEmptyString(report.project?.client_name);
  const orgFallbackName = nonEmptyString(report.organization?.name);

  const projectEligible = report.project_id !== null && (hasWhiteLabelSignals(projectConfig) || projectFallbackName !== null);
  const orgEligible = hasWhiteLabelSignals(orgConfig);

  const source: WhiteLabelSource = projectEligible ? "project" : orgEligible ? "organization" : "platform";

  const brandName =
    extractBrandName(projectConfig) ??
    projectFallbackName ??
    extractBrandName(orgConfig) ??
    orgFallbackName ??
    platform.brandName;

  const logoUrl = extractLogoUrl(projectConfig) ?? extractLogoUrl(orgConfig) ?? platform.logoUrl;

  const disclaimers = (() => {
    const projectDisclaimers = extractDisclaimers(projectConfig);
    if (projectDisclaimers.length > 0) return projectDisclaimers;

    const orgDisclaimers = extractDisclaimers(orgConfig);
    if (orgDisclaimers.length > 0) return orgDisclaimers;

    return platform.disclaimers;
  })();

  const showPlatformBranding =
    source === "project"
      ? false
      : extractShowPlatformBranding(source === "organization" ? orgConfig : {}) ?? platform.showPlatformBranding;

  return {
    source,
    brandName,
    logoUrl,
    disclaimers,
    showPlatformBranding
  };
}
