create or replace function public.resolve_report_white_label(
  p_report_id uuid,
  p_platform_defaults jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  report_row record;
  project_config jsonb := '{}'::jsonb;
  org_config jsonb := '{}'::jsonb;
  platform_config jsonb := coalesce(p_platform_defaults, '{}'::jsonb);
  source_label text := 'platform';
  brand_name text;
  logo_url text;
  disclaimers jsonb := '[]'::jsonb;
  show_platform_branding boolean := true;
  project_has_branding boolean := false;
  org_has_branding boolean := false;
begin
  select
    r.id,
    r.project_id,
    r.org_id,
    o.name as org_name,
    o.white_label_config as org_white_label_config,
    p.client_name,
    p.white_label_config as project_white_label_config
  into report_row
  from public.reports r
  join public.organizations o on o.id = r.org_id
  left join public.projects p on p.id = r.project_id
  where r.id = p_report_id
    and r.org_id = public.current_active_org();

  if not found then
    raise exception 'report not found or not visible in active org';
  end if;

  project_config := coalesce(report_row.project_white_label_config, '{}'::jsonb);
  org_config := coalesce(report_row.org_white_label_config, '{}'::jsonb);

  project_has_branding := report_row.project_id is not null and (
    nullif(project_config ->> 'brand_name', '') is not null
    or nullif(project_config ->> 'logo_url', '') is not null
    or nullif(project_config ->> 'logo', '') is not null
    or nullif(project_config ->> 'disclaimer', '') is not null
    or (jsonb_typeof(project_config -> 'disclaimers') = 'array' and jsonb_array_length(project_config -> 'disclaimers') > 0)
    or nullif(report_row.client_name, '') is not null
  );

  org_has_branding := (
    nullif(org_config ->> 'brand_name', '') is not null
    or nullif(org_config ->> 'logo_url', '') is not null
    or nullif(org_config ->> 'logo', '') is not null
    or nullif(org_config ->> 'disclaimer', '') is not null
    or (jsonb_typeof(org_config -> 'disclaimers') = 'array' and jsonb_array_length(org_config -> 'disclaimers') > 0)
    );

  if project_has_branding then
    source_label := 'project';
  elsif org_has_branding then
    source_label := 'organization';
  else
    source_label := 'platform';
  end if;

  brand_name := coalesce(
    nullif(project_config ->> 'brand_name', ''),
    nullif(report_row.client_name, ''),
    nullif(org_config ->> 'brand_name', ''),
    nullif(report_row.org_name, ''),
    nullif(platform_config ->> 'brand_name', ''),
    'Diligence OS'
  );

  logo_url := coalesce(
    nullif(project_config ->> 'logo_url', ''),
    nullif(project_config ->> 'logo', ''),
    nullif(org_config ->> 'logo_url', ''),
    nullif(org_config ->> 'logo', ''),
    nullif(platform_config ->> 'logo_url', ''),
    nullif(platform_config ->> 'logo', '')
  );

  if jsonb_typeof(project_config -> 'disclaimers') = 'array' and jsonb_array_length(project_config -> 'disclaimers') > 0 then
    disclaimers := project_config -> 'disclaimers';
  elsif nullif(project_config ->> 'disclaimer', '') is not null then
    disclaimers := jsonb_build_array(project_config ->> 'disclaimer');
  elsif jsonb_typeof(org_config -> 'disclaimers') = 'array' and jsonb_array_length(org_config -> 'disclaimers') > 0 then
    disclaimers := org_config -> 'disclaimers';
  elsif nullif(org_config ->> 'disclaimer', '') is not null then
    disclaimers := jsonb_build_array(org_config ->> 'disclaimer');
  elsif jsonb_typeof(platform_config -> 'disclaimers') = 'array' and jsonb_array_length(platform_config -> 'disclaimers') > 0 then
    disclaimers := platform_config -> 'disclaimers';
  elsif nullif(platform_config ->> 'disclaimer', '') is not null then
    disclaimers := jsonb_build_array(platform_config ->> 'disclaimer');
  else
    disclaimers := jsonb_build_array('Generated by Diligence OS. For informational purposes only.');
  end if;

  if source_label = 'project' then
    show_platform_branding := false;
  elsif source_label = 'organization' then
    show_platform_branding := coalesce(
      (org_config ->> 'show_platform_branding')::boolean,
      (org_config ->> 'include_platform_branding')::boolean,
      (platform_config ->> 'show_platform_branding')::boolean,
      (platform_config ->> 'include_platform_branding')::boolean,
      true
    );
  else
    show_platform_branding := coalesce(
      (platform_config ->> 'show_platform_branding')::boolean,
      (platform_config ->> 'include_platform_branding')::boolean,
      true
    );
  end if;

  return jsonb_build_object(
    'source', source_label,
    'brand_name', brand_name,
    'logo_url', logo_url,
    'disclaimers', disclaimers,
    'show_platform_branding', show_platform_branding
  );
end;
$$;

grant execute on function public.resolve_report_white_label(uuid, jsonb) to authenticated;
revoke execute on function public.resolve_report_white_label(uuid, jsonb) from anon, public;
